language: bash
services: docker

env:
  global:
      - DOCKER_COMPOSE_VERSION=1.23.0
      - secure: "YwAvdrjzfanHStyvLJwgnhrQ1g48rdeY74pXfEKgk4iTZ6E8y/wrQ1GK+PoUhNqvm6I079Nq12CrbVRbVH405NUjD6nFj4dq4g2MJwq+YDds2YL/2o1O6gf5TGT95UNeRlyCD9jtNKijPIRVdqoysT5UXwPH+TH+FplMQhrPqGOfh/95c7ObJ/C/Y/0xMHbAslV+jEr1Ctpa0hUnHjdmle1JZ6HlhBQ+WVOov0LY8FkLDVd80qhualWzgnYaxe/jY1rKwq4yU4tue8k00BewtRE/3DwEYCUjwjEhpWcH3CZvpQPqPx2a6PyoZgaVsZwsLQfHvOuNa9svAVaNIIOfy13IqI55qPnpBGTUQqJIB1i7yVRsptuj7bWf5aGdlvxqS1QU8GOFzOIDXKgSe4V+10l3iwbvL/4nq7GsTjvcxs8jbl2DtDzT18wUCFYAUjrRXS0Pw0TfUq7zrM47799yibiuEqfmriLvh1DJnUZ5MaiXK/5STgpJ/DDYVSPeAYcr7adg+8Q/gVNAyLLIWcNyV4Uhi10RXZm7hRnGP5WhnHHK6Pbt08GHtlXuK++KJ/XcAYbUYQP+OaCH/cr1P8SIRppRRuIYTgFyZYiG+FBjX0q93DkALoFQwZhdSryJ6Y6rVvOIvp9DP15/sKD6Q5AfoNDdBKFYtfJQJVuoQ/vwhRI="

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export IMAGE=instapy_sa
  - export TARGET_USER=futmoji_k455
  - export TARGET_PASSWORD=${TARGET_PASSWORD}

script:
  - |
    (
      set -xe
      docker-compose up
    )

after_script:
  - docker images

